// src/components/DrawAngledLine.vue
<script setup lang="ts">
import { controlPoint } from '../helpers/controlPoint';

const props = defineProps({
  startRadius: {type: Number, required: true},
  endRadius: {type: Number, required: true},
  angle: {type: Number, required: true},
  color: String,
  width: Number,
})
    
const [startX, startY] = controlPoint(props.startRadius, props.angle)
const [endX, endY] = controlPoint(props.endRadius, props.angle)

</script>

<template>
  <v-line
    :points="[startX, startY, endX, endY]"
    :stroke="color"
    :strokeWidth="width"
  />
</template>

<style scoped>
</style>

// src/legacy/DrawAngledLine.jsx
import React from 'react'
import * as Canvas from 'react-konva'
import { controlPoint } from './DrawCanvas'

export default function ({
    x,
    y,
    startRadius,
    endRadius,
    angle,
    color,
    width,
}) {
    let [startX, startY] = controlPoint(x, y, startRadius, angle)
    let [endX, endY] = controlPoint(x, y, endRadius, angle)
    return (
        <>
            <Canvas.Line
                points={[startX, startY, endX, endY]}
                stroke={color}
                strokeWidth={width}
            />
        </>
    )
}
