// src/components/DrawBase.vue
<script setup>
import { useParamStore } from '../store/paramStore';
import DrawSector from './DrawSector.vue';
import TypeDivider from './TypeDivider.vue';

const store = useParamStore()

const props = defineProps({
  bgColor: String,
  bgColor2: String,
  sectors: Array,
})
    
const emit = defineEmits(['setClickedInfo', "setClickedSector"])

const setClickedInfo = () => {}

const setClickedSector = () => {}

console.log(props.sectors)

</script>

<template>
  <DrawSector
    v-for="sector of sectors"
    :sector="sector"
    :bgColor="sector.sLevel % 2 === 0 ? bgColor : bgColor2"
    @setClickedInfo="setClickedInfo"
    @setClickedSector="setClickedSector"
  />
  <TypeDivider
    v-for="dAngle of store.params.dividerAngles"
    :startRadius="store.params.innerRadius"
    :endRadius="store.params.outerRadius + 50 * store.circleNum * store.scaleMultiplier"
    :angle="dAngle"
  />
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// src/legacy/DrawBase.jsx
import React from 'react'
import * as Canvas from 'react-konva'
import DrawSector from './DrawSector'
import DrawAngledLine from './DrawAngledLine'
export default function ({
    x,
    y,
    params,
    scaleMultiplicator,
    sizeMultiplier,
    bgColor,
    bgColor2,
    sectors,
    circleNum,
    flags,
    setClickedInfo,
    setClickedSector,
}) {
    let drawSectors = []
    let drawDivider = []
    sectors.map(sector => {
        drawSectors.push(
            <DrawSector
                x={x}
                y={y}
                sector={sector}
                params={params}
                bgColor={sector.sLevel % 2 === 0 ? bgColor : bgColor2}
                scaleMultiplicator={scaleMultiplicator}
                sizeMultiplier={sizeMultiplier}
                flags={flags}
                setClickedInfo={setClickedInfo}
                setClickedSector={setClickedSector}
            />,
        )
    })
    params.dividerAngles.map(dAngle => {
        drawDivider.push(
            <TypeDivider
                x={x}
                y={y}
                startRadius={params.innerRadius}
                endRadius={
                    params.outerRadius + 50 * circleNum * scaleMultiplicator
                }
                angle={dAngle}
                scaleMultiplicator={scaleMultiplicator}
            />,
        )
    })

    return (
        <>
            {drawSectors}
            {drawDivider}
        </>
    )
}

function TypeDivider({
    x,
    y,
    startRadius,
    endRadius,
    angle,
    scaleMultiplicator,
}) {
    return (
        <>
            <DrawAngledLine
                x={x}
                y={y}
                startRadius={startRadius}
                endRadius={endRadius}
                angle={angle}
                color={'black'}
                width={5 * scaleMultiplicator}
            />
            <DrawAngledLine
                x={x}
                y={y}
                startRadius={startRadius - 2}
                endRadius={endRadius + 2}
                angle={angle}
                color={'white'}
                width={2 * scaleMultiplicator}
            />
        </>
    )
}
