// src/legacy/DrawSector.jsx
import React from 'react'
import * as Canvas from 'react-konva'
import {controlPoint} from './DrawCanvas'

export default function DrawSector({
    x,
    y,
    sector,
    params,
    bgColor,
    scaleMultiplicator,
    sizeMultiplier,
    flags,
    shadowed,
    setClickedInfo,
    setClickedSector,
    opacity,
}) {
    const [fill, setFill] = React.useState(bgColor)
    const [scale, setScale] = React.useState(1)
    let arcLength = sector.sEnd - sector.sStart
    let r = 0
    if (sector.sEnd - arcLength / 2 > 90 && sector.sEnd - arcLength / 2 < 270)
        r = 1
    const handleClick = (event) => {
        if (flags.oneLevel) {
            setClickedInfo({
                type: 'sector',
                id: sector.upperID,
            })
            setClickedSector({
                isClicked: true,
                sector: sector,
            })
        }

        //console.log('clicked sector of ' + sector.upperID)
    }
    const [labelX, labelY] = controlPoint(
        x,
        y,
        params.labelRadius + 50 * sector.sLevel * scaleMultiplicator,
        90 + (sector.sEnd - arcLength / 2)
    )
    let additional = 0
    if (flags.showSupportRect) {
        additional = 50
    }
    const [nameX, nameY] = controlPoint(
        x,
        y,
        params.sectorNameRadius + additional,
        90 + (sector.sEnd - arcLength / 2)
    )
    let fillColor = 'white'
    if (sector.objLabel) {
        if (sector.objLabel.score > 0) {
            fillColor = 'green'
        }
        if (sector.objLabel.score < 0) {
            fillColor = 'red'
        }
    }
    return (
        <>
            <Canvas.Arc
                x={x}
                y={y}
                angle={360 - arcLength}
                rotation={-90 - sector.sStart}
                outerRadius={
                    params.outerRadius + 50 * sector.sLevel * scaleMultiplicator
                }
                innerRadius={
                    params.innerRadius + 50 * sector.sLevel * scaleMultiplicator
                }
                fill={fill}
                stroke='black'
                opacity={opacity}
                onClick={handleClick}
                onMouseOver={() => {
                    setFill('gray')
                }}
                onMouseOut={() => {
                    setFill(bgColor)
                }}
                clockwise
                strokeWidth={2 * scaleMultiplicator}
            />
            {flags.showSectorName && (
                <>
                    <Canvas.Text
                        x={nameX}
                        y={nameY}
                        text={sector.shortname}
                        offset={{
                            x: 20 * sizeMultiplier * scale * scaleMultiplicator,
                            y: 10 * sizeMultiplier * scale * scaleMultiplicator,
                        }}
                        fontFamily='Times New Roman'
                        fontSize={
                            22 * sizeMultiplier * scale * scaleMultiplicator
                        }
                        onClick={handleClick}
                        onMouseOver={() => {
                            setFill('gray')
                        }}
                        onMouseOut={() => {
                            setFill(bgColor)
                        }}
                        rotation={-(sector.sEnd - arcLength / 2) - 180 * r}
                    />
                </>
            )}
            {sector.objLabel && sector.objLabel.isLabel && (
                <>
                    <Canvas.Rect
                        x={labelX}
                        y={labelY}
                        width={36 * sizeMultiplier * scale * scaleMultiplicator}
                        height={
                            36 * sizeMultiplier * scale * scaleMultiplicator
                        }
                        fill={'white'}
                        stroke={'black'}
                        strokeWidth={1 * scaleMultiplicator}
                        onClick={handleClick}
                        offset={{
                            x: 18 * sizeMultiplier * scale * scaleMultiplicator,
                            y: 18 * sizeMultiplier * scale * scaleMultiplicator,
                        }}
                        rotation={-(sector.sEnd - arcLength / 2)}
                        onMouseOver={() => {
                            setScale(1.5)
                        }}
                        onMouseOut={() => {
                            setScale(1)
                        }}
                    />
                    {flags.showScore && (
                        <Canvas.Rect
                            x={labelX}
                            y={labelY}
                            width={
                                36 * sizeMultiplier * scale * scaleMultiplicator
                            }
                            height={
                                36 * sizeMultiplier * scale * scaleMultiplicator
                            }
                            opacity={Math.abs(sector.objLabel.score)}
                            fill={shadowed ? 'white' : fillColor}
                            stroke={shadowed ? fillColor : 'black'}
                            strokeWidth={1 * scaleMultiplicator}
                            onClick={handleClick}
                            offset={{
                                x:
                                    18 *
                                    sizeMultiplier *
                                    scale *
                                    scaleMultiplicator,
                                y:
                                    18 *
                                    sizeMultiplier *
                                    scale *
                                    scaleMultiplicator,
                            }}
                            rotation={-(sector.sEnd - arcLength / 2)}
                            onMouseOver={() => {
                                setScale(1.5)
                            }}
                            onMouseOut={() => {
                                setScale(1)
                            }}
                        />
                    )}
                    <Canvas.Text
                        x={labelX}
                        y={labelY}
                        text={sector.objLabel.typeText}
                        offset={{
                            x: 13 * sizeMultiplier * scale * scaleMultiplicator,
                            y: 10 * sizeMultiplier * scale * scaleMultiplicator,
                        }}
                        fontFamily='Times New Roman'
                        fontSize={
                            22 * sizeMultiplier * scale * scaleMultiplicator
                        }
                        onClick={handleClick}
                        onMouseOver={() => {
                            setScale(1.5)
                        }}
                        onMouseOut={() => {
                            setScale(1)
                        }}
                        fontStyle={sector.objLabel.fontStyle}
                    />
                    <Canvas.Text
                        x={labelX}
                        y={labelY}
                        text={sector.objLabel.numText}
                        offset={{
                            x: 1 * sizeMultiplier * scale * scaleMultiplicator,
                            y: 2 * sizeMultiplier * scale * scaleMultiplicator,
                        }}
                        fontFamily='Times New Roman'
                        fontSize={
                            16 * sizeMultiplier * scale * scaleMultiplicator
                        }
                        onClick={handleClick}
                        onMouseOver={() => {
                            setScale(1.5)
                        }}
                        onMouseOut={() => {
                            setScale(1)
                        }}
                        fontStyle={sector.objLabel.fontStyle}
                    />
                </>
            )}
            {sector.objLabel && !sector.objLabel.isLabel && (
                <>
                    <Canvas.Text
                        x={labelX}
                        y={labelY}
                        text={
                            sector.objLabel.typeText + sector.objLabel.numText
                        }
                        offset={{
                            x: 20 * sizeMultiplier * scale * scaleMultiplicator,
                            y: 10 * sizeMultiplier * scale * scaleMultiplicator,
                        }}
                        fontFamily='Times New Roman'
                        fontSize={
                            22 * sizeMultiplier * scale * scaleMultiplicator
                        }
                        onClick={handleClick}
                        onMouseOver={() => {
                            setFill('gray')
                        }}
                        onMouseOut={() => {
                            setFill(bgColor)
                        }}
                        rotation={-(sector.sEnd - arcLength / 2) - 180 * r}
                        fontStyle={sector.objLabel.fontStyle}
                    />
                </>
            )}
        </>
    )
}

// src/components/DrawSector.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useParamStore } from "../store/paramStore";
import { useClickedStore } from "../store/clickedStore";
import { calcControlPoint } from "../helpers/calcControlPoint";
import type { Sector } from "../types/sector";

const store = useParamStore();
const clickedStore = useClickedStore();

const props = defineProps<{
  sector: Sector;
  bgColor: string;
  shadowed?: boolean;
  opacity?: number;
}>();

const fill = ref(props.bgColor);

const handleClick = () => {
  clickedStore.setClickedSector(props.sector);
};

const handleMouseOver = () => {
  fill.value = "gray";
};

const handleMouseOut = () => {
  fill.value = props.bgColor;
};

const targetAngle = computed(
  () => props.sector.sEnd - (props.sector.sEnd - props.sector.sStart) / 2,
);

const arcLength = computed(() => props.sector.sEnd - props.sector.sStart);

const labelXY = computed<[number, number]>(() => {
  return calcControlPoint(
    store.radiuses.value.labelRadius +
      50 * props.sector.sLevel * store.scaleMultiplier.value,
    90 + targetAngle.value,
  );
});

const nameXY = computed<[number, number]>(() => {
  return calcControlPoint(
    store.radiuses.value.sectorNameRadius,
    90 + targetAngle.value,
  );
});

const labelFillColor = computed(() => {
  if (props.sector.object.score > 0) {
    return "green";
  }
  if (props.sector.object.score < 0) {
    return "red";
  }
  return "white";
});

const sectorWithLabel = computed(() => {
  if (props.sector.object.isLabel && props.sector.object.level > 0) return true;
  else return false;
});

const coeff = computed(() => {
  return store.sizeMultiplier.value * store.scaleMultiplier.value;
});

const nameRotation = computed(() => {
  const angleCorrection =
    targetAngle.value > 90 && targetAngle.value < 270 ? 1 : 0;

  return -(props.sector.sEnd - arcLength.value / 2) - 180 * angleCorrection;
});

const outerRadius = computed(
  () =>
    store.radiuses.value.outerRadius +
    50 * props.sector.sLevel * store.scaleMultiplier.value,
);

const innerRadius = computed(
  () =>
    store.radiuses.value.innerRadius +
    50 * props.sector.sLevel * store.scaleMultiplier.value,
);

const labelConfig = computed(() => ({
  x: labelXY.value[0],
  y: labelXY.value[1],
  width: 36 * coeff.value,
  height: 36 * coeff.value,
  strokeWidth: 1 * store.scaleMultiplier.value,
  offsetX: 18 * coeff.value,
  offsetY: 18 * coeff.value,
  rotation: -(props.sector.sEnd - arcLength.value / 2),
}));

const textConfig = computed(() => ({
  x: labelXY.value[0],
  y: labelXY.value[1],
  fontFamily: "Times New Roman",
  fontStyle: props.sector.object.fontStyle,
  fontSize: 22 * coeff.value,
}));
</script>

<template>
  <v-arc
    :x="store.centerPoint.value"
    :y="store.centerPoint.value"
    :angle="360 - arcLength"
    :rotation="-90 - sector.sStart"
    :outerRadius="outerRadius"
    :innerRadius="innerRadius"
    :fill="fill"
    stroke="black"
    :opacity="opacity"
    :clockwise="true"
    :strokeWidth="2 * store.scaleMultiplier.value"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
  <v-text
    v-if="store.showSectorName.value"
    :config="{
      ...textConfig,
      x: nameXY[0],
      y: nameXY[1],
    }"
    :text="sector.shortname"
    :offsetX="10 * coeff"
    :offsetY="10 * coeff"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
  <v-rect
    v-if="sectorWithLabel"
    :config="labelConfig"
    fill="white"
    stroke="black"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
  <v-rect
    v-if="sectorWithLabel && store.showScore.value"
    :config="labelConfig"
    :opacity="Math.abs(sector.object.score)"
    :fill="shadowed ? 'white' : labelFillColor"
    :stroke="shadowed ? labelFillColor : 'black'"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
  <v-text
    v-if="sectorWithLabel"
    :key="`${store.reloadCount.value}-${sector.object.id}-sectorlabel-type-text`"
    :config="textConfig"
    :text="sector.object.typeText"
    :offsetX="13 * coeff"
    :offsetY="10 * coeff"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
  <v-text
    v-if="sectorWithLabel"
    :key="`${store.reloadCount.value}-${sector.object.id}-sectorlabel-num-text`"
    :config="{
      ...textConfig,
      fontSize: 16 * coeff,
    }"
    :text="sector.object.numText"
    :offsetX="1 * coeff"
    :offsetY="2 * coeff"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
  <v-text
    v-if="!sectorWithLabel && sector.object.level != 0"
    :key="`${store.reloadCount.value}-${sector.object.id}-sector-text`"
    :config="textConfig"
    :text="sector.object.typeText + sector.object.numText"
    :offsetX="10 * coeff"
    :offsetY="20 * coeff"
    :rotation="nameRotation"
    @click="handleClick"
    @mouse-over="handleMouseOver"
    @mouse-out="handleMouseOut"
  />
</template>
